# Generated by Django 6.0.8 on 2026-09-09 17:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=50)),
                ('floor', models.PositiveIntegerField()),
                ('flat_type', models.CharField(choices=[('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK'), ('Penthouse', 'Penthouse'), ('Studio', 'Studio')], max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('base_maintenance_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['block', 'flat_number'],
                'unique_together': {('flat_number', 'block')},
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('Resident', 'Resident'), ('Guard', 'Guard'), ('Admin', 'Admin')], default='Resident', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Moved-out', 'Moved-out')], default='Active', max_length=20)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='residents', to='api.flat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC / Air Conditioning'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('pest_control', 'Pest Control'), ('appliance', 'Appliance Repair'), ('elevator', 'Elevator'), ('common_area', 'Common Area / Housekeeping'), ('water_supply', 'Water Supply'), ('internet', 'Internet / Cabling'), ('security', 'Security'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='maintenance_requests', to='api.flat')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('Base Maintenance', 'Base Maintenance'), ('Additional Charge', 'Additional Charge')], default='Base Maintenance', max_length=30)),
                ('billing_month', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Cash', 'Cash')], max_length=20, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='api.flat')),
                ('source_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='api.maintenancerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('contact_number', models.CharField(max_length=15)),
                ('purpose', models.CharField(choices=[('Delivery', 'Delivery'), ('Guest', 'Guest'), ('Service/Maintenance', 'Service/Maintenance'), ('Other', 'Other')], max_length=30)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('Car', 'Car'), ('Bike', 'Bike'), ('None', 'None')], max_length=10, null=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Inside', 'Inside'), ('Checked-Out', 'Checked-Out')], default='Inside', max_length=20)),
                ('target_flat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='visitors', to='api.flat')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
    ]
