# Generated by Django 6.0.8 on 2026-09-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='manually_marked_occupied',
            field=models.BooleanField(default=False, help_text="Use this if a resident is living here but doesn't have a portal account yet."),
        ),
    ]
